import numpy as np
from scipy.interpolate import CloughTocher2DInterpolator

class Phase:
    """Thermodynamic properties of a phase calculated by gibbs2. This class
    is derived from the information written to a .eos file and is used
    to create plots and performing tasks not done in gibbs2 by default."""

    ## constructor
    def __init__(self,name,strl):
        """Constructor for the phase. name is the name of the phase
        and strl is a list of strings with the thermodynamic
        properties obtained from reading the eos file (see
        examples)."""

        self._name = name

        ## read the data
        x = np.genfromtxt(strl)
        self._plist = x[:,0]
        self._Tlist = x[:,1]
        self._Vlist = x[:,2]
        self._Glist = x[:,4]

        ## unique temperatures and pressures to within 2 decimal places
        self._Tkeys = np.unique(np.sort(np.round(self._Tlist,decimals=2)))
        self._pkeys = np.unique(np.sort(np.round(self._plist,decimals=2)))

        ## set up thte interpolant
        self._Ginterp = CloughTocher2DInterpolator(list(zip(self._plist, self._Tlist)), self._Glist)

    ## interpolated thermodynamic properties
    def G(self,p,T):
        """Returns the interpolated Gibbs energy."""
        return self._Ginterp((p,T))

    ## some properties: min, max, step temperature and pressure, name
    @property
    def Tmin(self):
        return np.min(self._Tlist)
    @property
    def Tmax(self):
        return np.max(self._Tlist)
    @property
    def pmin(self):
        return np.min(self._plist)
    @property
    def pmax(self):
        return np.max(self._plist)
    @property
    def Tstep(self):
        return np.min(np.diff(np.unique(np.sort(self._Tlist))))
    @property
    def pstep(self):
        return np.min(np.diff(np.unique(np.sort(self._plist))))
    @property
    def name(self):
        return self._name

    ## representation functions
    def __str__(self):
        return f"Phase {self._name} with {len(self._pkeys)} pressures and {len(self._Tkeys)} temperatures."

def read_phases_from_eos_file(eosfile):
    """Read a .eos file generated by gibbs2 and return a list of phases containing
    all calculated thermodynamic properties."""

    phlist = []
    name = None
    with open(eosfile,"r") as f:
        for line in f:
            if line.startswith("# Phase"):
                if name is not None:
                    phlist.append(Phase(name,strl))
                name = line.split()[-1]
                strl = []
            if name is not None and not line.startswith("#"):
                strl.append(line)
    if name is not None:
        phlist.append(Phase(name,strl))

    return phlist
